const DEFAULT_TIMESTAMP = "2026-04-10T10:00:00";

function clone(value) {
  return JSON.parse(JSON.stringify(value));
}

function createPaginationState() {
  return {
    inventory: { page: 1, pageSize: 10, total: 0 },
    companies: { page: 1, pageSize: 10, total: 0 },
    suppliers: { page: 1, pageSize: 10, total: 0 },
    customers: { page: 1, pageSize: 10, total: 0 },
    stock: { page: 1, pageSize: 10, total: 0 },
    logs: { page: 1, pageSize: 10, total: 0 },
    bills: { page: 1, pageSize: 10, total: 0 },
  };
}

function createFixtureData() {
  return clone({
    currentUser: {
      id: "U001",
      name: "Tester",
      role: "admin",
    },
    clientIP: "127.0.0.1",
    mockData: {
      products: [
        {
          id: "P001",
          name: "Widget",
          category: "电子产品",
          unit: "个",
          costPrice: 100,
          retailPrice: 150,
          stockQuantity: 20,
          minStock: 5,
          maxStock: 50,
          supplierId: "S001",
          createdAt: DEFAULT_TIMESTAMP,
          updatedAt: DEFAULT_TIMESTAMP,
        },
        {
          id: "P002",
          name: "Gadget",
          category: "图书",
          unit: "件",
          costPrice: 40,
          retailPrice: 60,
          stockQuantity: 8,
          minStock: 3,
          maxStock: 30,
          supplierId: "S002",
          createdAt: DEFAULT_TIMESTAMP,
          updatedAt: DEFAULT_TIMESTAMP,
        },
      ],
      suppliers: [
        {
          id: "S001",
          name: "Acme Supply",
          contactPerson: "Alice",
          contactPhone: "13800138000",
          email: "alice@example.com",
          address: "Shenzhen",
          paymentTerms: "Net 30",
          creditLimit: 0,
          status: "active",
          createdAt: DEFAULT_TIMESTAMP,
          updatedAt: DEFAULT_TIMESTAMP,
        },
        {
          id: "S002",
          name: "Bravo Parts",
          contactPerson: "Bruce",
          contactPhone: "13900139000",
          email: "bruce@example.com",
          address: "Suzhou",
          paymentTerms: "COD",
          creditLimit: 0,
          status: "active",
          createdAt: DEFAULT_TIMESTAMP,
          updatedAt: DEFAULT_TIMESTAMP,
        },
      ],
      customers: [
        {
          id: "C001",
          name: "Northwind",
          contactPerson: "Nina",
          contactPhone: "13700137000",
          address: "Shanghai",
          email: "nina@example.com",
          paymentTerms: "Net 30",
          creditLimit: 0,
          status: "active",
          createdAt: DEFAULT_TIMESTAMP,
          updatedAt: DEFAULT_TIMESTAMP,
        },
        {
          id: "C002",
          name: "Acorn Retail",
          contactPerson: "Aaron",
          contactPhone: "13600136000",
          address: "Hangzhou",
          email: "aaron@example.com",
          paymentTerms: "Net 45",
          creditLimit: 0,
          status: "inactive",
          createdAt: DEFAULT_TIMESTAMP,
          updatedAt: DEFAULT_TIMESTAMP,
        },
      ],
      companies: [
        {
          id: "CO001",
          name: "Happy Warehouse",
          contactPerson: "Carol",
          contactPhone: "13500135000",
          address: "Guangzhou",
          email: "carol@example.com",
          status: "active",
          createdAt: DEFAULT_TIMESTAMP,
          updatedAt: DEFAULT_TIMESTAMP,
        },
        {
          id: "CO002",
          name: "Backup Warehouse",
          contactPerson: "Ben",
          contactPhone: "13400134000",
          address: "Nanjing",
          email: "ben@example.com",
          status: "active",
          createdAt: DEFAULT_TIMESTAMP,
          updatedAt: DEFAULT_TIMESTAMP,
        },
      ],
      bills: [
        {
          id: "BILL-C-001",
          recordType: "statement-v1",
          statementType: "customer",
          partyId: "C001",
          partyNameSnapshot: "Northwind",
          periodStart: "2026-04-01",
          periodEnd: "2026-04-15",
          statementDate: "2026-04-16",
          totalAmount: 1200,
          status: "pending_payment",
          payments: [],
          createdAt: "2026-04-16T08:00:00",
          updatedAt: "2026-04-16T10:00:00",
        },
        {
          id: "BILL-S-001",
          recordType: "statement-v1",
          statementType: "supplier",
          partyId: "S001",
          partyNameSnapshot: "Acme Supply",
          periodStart: "2026-04-01",
          periodEnd: "2026-04-15",
          statementDate: "2026-04-16",
          totalAmount: 600,
          status: "paid",
          payments: [{ id: "PAY-1", payAmount: 600 }],
          createdAt: "2026-04-15T08:00:00",
          updatedAt: "2026-04-15T10:00:00",
        },
        {
          id: "BILL-C-002",
          recordType: "statement-v1",
          statementType: "customer",
          partyId: "C002",
          partyNameSnapshot: "Acorn Retail",
          periodStart: "2026-04-01",
          periodEnd: "2026-04-15",
          statementDate: "2026-04-17",
          totalAmount: 300,
          status: "partial_paid",
          payments: [{ id: "PAY-2", payAmount: 100 }],
          createdAt: "2026-04-17T08:00:00",
          updatedAt: "2026-04-17T10:00:00",
        },
      ],
      deliveryNotes: [],
    },
    stockMovementData: [
      {
        id: "SM001",
        type: "inbound",
        productId: "P001",
        productName: "Widget",
        quantity: 5,
        unit: "个",
        supplierId: "S001",
        supplierName: "Acme Supply",
        operator: "Tester",
        remark: "Initial restock",
        createdAt: "2026-04-10T09:00:00",
        updatedAt: "2026-04-10T09:00:00",
      },
      {
        id: "SM002",
        type: "outbound",
        productId: "P002",
        productName: "Gadget",
        quantity: 2,
        unit: "件",
        operator: "Tester",
        remark: "Initial shipment",
        createdAt: "2026-04-11T09:00:00",
        updatedAt: "2026-04-11T09:00:00",
      },
    ],
    logsData: [
      {
        id: "LOG001",
        timestamp: "2026-04-11T11:00:00",
        userId: "U001",
        userName: "Tester",
        actionType: "add",
        objectType: "product",
        objectName: "Widget",
        details: "Created widget",
        ipAddress: "127.0.0.1",
      },
      {
        id: "LOG002",
        timestamp: "2026-04-12T11:00:00",
        userId: "U002",
        userName: "Auditor",
        actionType: "edit",
        objectType: "supplier",
        objectName: "Acme Supply",
        details: "Updated supplier",
        ipAddress: "127.0.0.2",
      },
    ],
    paginationState: createPaginationState(),
  });
}

module.exports = {
  clone,
  createFixtureData,
  createPaginationState,
};
